### ISSUE TITLE
Setup Instructions Don't Work

### ISSUE THREAD

**Issue by ries9112** [decentraland/atlas-server#21]
I have tried getting this to work on both my Windows PC and my MacBook, and neither seems to work when I run `npm start`.

This is what I'm seeing:
![image](https://user-images.githubusercontent.com/32306488/108013722-7e1ef600-6fc9-11eb-9298-2be4a44769c4.png)

And here are the logs:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle atlas-server@1.0.0~prestart: atlas-server@1.0.0
6 info lifecycle atlas-server@1.0.0~start: atlas-server@1.0.0
7 verbose lifecycle atlas-server@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle atlas-server@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Ricky\Desktop\atlas-server\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Ricky\bin;C:\rtools40\usr\bin;C:\Program Files\R\R-3.6.2\bin\x64;C:\Rtools\bin;C:\Program Files\Oculus\Support\oculus-runtime;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\MiKTeX 2.9\miktex\bin\x64;C:\ProgramData\Anaconda3\python.exe;C:\Program Files\Alteryx\bin\AlteryxEngineCmd.exe;C:\Program Files\Amazon\AWSCLI;C:\Program Files\PuTTY;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet;C:\Program Files\CMake\bin;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.4.0;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Users\Ricky\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Alteryx\bin\AlteryxEngineCmd.exe;C:\Users\Ricky\AppData\Local\GitHubDesktop\bin;C:\Users\Ricky\AppData\Roaming\TinyTeX\bin\win32;C:\Program Files\Docker Toolbox;C:\Users\Ricky\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Ricky\AppData\Roaming\npm;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Git\usr\bin;C:\Program Files\RStudio\bin\msys-ssh-1000-18
9 verbose lifecycle atlas-server@1.0.0~start: CWD: C:\Users\Ricky\Desktop\atlas-server
10 silly lifecycle atlas-server@1.0.0~start: Args: [ '/d /s /c', 'node dist' ]
11 silly lifecycle atlas-server@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle atlas-server@1.0.0~start: Failed to exec start script
13 verbose stack Error: atlas-server@1.0.0 start: `node dist`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid atlas-server@1.0.0
15 verbose cwd C:\Users\Ricky\Desktop\atlas-server
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error atlas-server@1.0.0 start: `node dist`
22 error Exit status 1
23 error Failed at the atlas-server@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Are there any concrete examples on using either the 1.0 or the 2.0 API in Python or R? It is totally unclear how you are supposed to authenticate to make a GET request, I can't find a reference to this anywhere in the documentation. I also don't understand why these wouldn't be public endpoints. I pull data regularly from multiple API's, some of which require authentication, but I can't get this to work because there is absolutely 0 reference of how you are supposed to authenticate and no examples are given.

Would appreciate help understanding how to use the Decentraland API, I have been on the Discord #support-api channel asking about this for 10 days and have only gotten one useful short response saying I need to authenticate and that it's not easy, nobody seems to have an example or info outside of that. Please document this better or it's unusable!

**Comment by nachomazzara** [comment]
[This](https://github.com/decentraland/atlas-server/pull/22/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L8) may solve your issue

**Comment by ries9112** [comment]
Thank you, and apologies on the critical comment, this actually works really well and is very simple to use after-all, very cool tool, thank you
